coverage:
  range: "25...50"
  round: down
  precision: 2
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false 
  require_base: no
  require_head: ye
  branches: null

