language: go

branches:
  only:
    - master
    - develop

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

go:
  - "1.10"
os:
  - linux
  - osx

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - make build
  - make test
