language: go

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: osx
      osx_image: xcode10
      go: 1.10.x
      script:
        - make build
        - make test

    - os: linux
      dist: trusty
      go: 1.10.x
      services:
        - docker
      before_install:
        - make devimage
        - alias devimage='docker run -it --rm -v $(pwd):/gopath/src/github.com/iost-official/Go-IOS-Protocol iostio/iost-dev'
      script:
        - devimage make build
        - devimage make test

