language: go

branches:
  only:
    - master
    - develop
    - /^sprint.*$/

matrix:
  include:
    - os: osx
      osx_image: xcode10
      go: 1.10.x
      before_install:
        - brew install git-lfs
      script:
        - make build
        - make test

    - os: linux
      dist: trusty
      go: 1.10.x
      services:
        - docker
      before_install:
        - docker pull iostio/iost-dev
      script:
        - docker run -it --rm -v $(pwd):/gopath/src/github.com/iost-official/Go-IOS-Protocol iostio/iost-dev make build
        - docker run -it --rm -v $(pwd):/gopath/src/github.com/iost-official/Go-IOS-Protocol iostio/iost-dev make test
