language: go

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      go: 1.10
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - CC=gcc-5
         - CXX=g++-5
    - os: osx
      go: 1.10
      env:
         - CC=clang
         - CXX=clang++

before_install:
  - ${CC} --version
  - ${CXX} --version

install: true

script:
  - make build
  - make test
