acc:
  id: "IOST5FhLBhVXMnwWRwhvz5j9NyWpBSchAMzpSMZT21xZqT8w7icwJ5"
  seckey: "BCV7fV37aSWNx1N1Yjk3TdQXeHMmLhyqsqGms1PkqwPT"

vm:
  logLevel: "debug"
  jsPath: "vm/v8vm/v8/libjs/"
db:
  ldbpath: "leveldb/"


p2p:
  listenAddr: "0.0.0.0:30308"
  chainID: 1024
  version: 1
  seedNodes:
  - "/ip4/127.0.0.1/tcp/30308/ipfs/12D3KooWMH9UtmksK7dUXoHFUPuHSKAB4LwStPuzdijahDiPLdSR"

rpc:
  port: 30312

log:
  asyncWrite: true
  fileLog:
    path: "logs/"
    level: "info"
    enable: true
  consoleLog:
    level: "debug"
    enable: true
